# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

stopValue = 4000000
fib_lst = []
result = 0
next_num=1


while next_num <= stopValue:  
   if len(fib_lst) == 0:
      fib_lst.append(1)
   elif len(fib_lst) == 1:
      fib_lst.append(2)
      result=result + 2
   else:
      next_num = fib_lst[len(fib_lst) - 1 ] + fib_lst[len(fib_lst) - 2 ]
      if next_num%2 == 0 :
         result+=next_num
      fib_lst.pop(0)
      fib_lst.append(next_num)
   print(fib_lst)

print(result)